Pierre's side business
The client
Pierre's side business, Papa Pierre's Pâtisseries, delivers French yumminess to almost a thousand major locations around the world thanks to its technologically-advanced fleet of vehicles:

The CrappyCrepeCar is a flying car that can travel between any two cities in the world, but moves pretty slowly.


The DiplomacyDonutDinghy is a small boat which is licensed to travel on diplomatic hyperlanes. So it moves extra fast between capital cities. It can also travel between any two cities in the same country. However, it can only move from one country to another via their capitals.


The TeleportingTarteTrolley is a trolley bus that can teleport between any two cities if they are close enough, regardless of countries. Because teleportation technology is still in its infancy, it takes time to program and execute a blink between two cities.


All images have been generated by DALL·E. Clearly it's not yet very good at spelling.

The program
Your job is to create a program that will be used in these vehicles to help them travel between cities, by finding a shortest path between cities and creating a map of the trip.

As an example of what this could look like, we plotted below the trip Paris -> Kuala Lumpur -> Melbourne.